### ISSUE TITLE
Cannot execute npm run build:src && npm run start after npm install

### ISSUE THREAD

**Issue by alca259** [Norviah/animal-crossing#3]
[2021-03-24T00_07_03_738Z-debug.log](https://github.com/Norviah/animal-crossing/files/6193478/2021-03-24T00_07_03_738Z-debug.log)
Hello, i try to execute manually the code in vscode and i am not able to do it

![image](https://user-images.githubusercontent.com/3340608/112234674-4eed4b80-8c3d-11eb-9490-9ac932cbc834.png)
Log attached

**Comment by Norviah** [comment]
im sorry but what does the error say? the line above `npm ERR! code ELIFECYCLE`

**Comment by alca259** [comment]
Says "." is not recognized as internal or external command, program or batch file

Maybe is my node version?
using npm@6.14.8
using node@v14.15.0

**Comment by Norviah** [comment]
ok i see, i dont develop on windows so i never got this error before. when you run `npm run build:src` and `npm run start`, it runs a certain script in `package.json`, then the called script is what actually builds and runs the program. for example, for `build:src`, this script runs `./node_modules/typescript/bin/tsc`, in mac/linux, this is valid because it uses `./` which is a relative path to the build script for typescript. for windows, you'll have to use the absolute paths instead.

to fix this, first, in `package.json`, you want to edit the `build:src` and `start` script. first, change every forward slash (`/`) to a backslash (`\`). then,  you would have to replace certain values, you have to replace the beginning `.\` with the absolute path of the directory that you downloaded the project into. for example, if i downloaded the project into my downloads folder, i would replace `.\` with `C:\Users\norviah\Downloads` so that `.\node_modules\typescript\bin\tsc` becomes `C:\Users\norviah\Downloads\node_modules\typescript\bin\tsc`. do this change for every `.\` you see within the `build:src` and `start` script in `package.json`.

in addition, change the `build:src` script so it has a `node` before the path, for example, `node C:\Users\norviah\Downloads\node_modules\typescript\bin\tsc`.

**Comment by alca259** [comment]
thanks i'll try it tonight and tell you something

**Comment by alca259** [comment]
For other people to try to execute on Windows, change the shell to git bash or use visual studio code. [How to change shell on Windows](https://stackoverflow.com/questions/23243353/how-to-set-shell-for-npm-run-scripts-in-windows)
Change this line "build:src": "./node_modules/typescript/bin/tsc" for this line "build:src": "node ./node_modules/typescript/bin/tsc"
Change this line "/bin/rm -rf ./json/combined ./json/data ./json/raw && node ./build/index.js" for this line "start": "rm -rf ./json/combined ./json/data ./json/raw && node ./build/index.js"

You can run now the script :)

**Comment by Norviah** [comment]
aight thank ya for the insight
